title: Settings
data:
  site_name: 'Rohan Sakhale - Enterprise Solution Provider'
  social:
    -
      id: m77v6krz
      name: LinkedIn
      url: 'https://www.linkedin.com/in/rsakhale/'
      icon: site/social-icons/linkedin.svg
    -
      id: bWXVFUoD
      name: Twitter
      url: 'https://twitter.com/RohanSakhale'
      icon: site/social-icons/twitter.svg
    -
      id: BrQFX33K
      name: Github
      url: 'https://github.com/RohanSakhale'
      icon: site/social-icons/github.svg
    -
      id: 9vGomXW2
      name: Email
      url: 'mailto:rohan@saiashirwad.com'
      icon: site/social-icons/email.svg
